name: CMake-Windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  SDL_VERSION: 2.0.16

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    
    - name: submodules-init
      # You may pin to the exact commit or the version.
      uses: snickerbockers/submodules-init@v4
      
    - name: sync submodules to master
      shell: powershell
      run: git submodule foreach git pull origin master
      
    - name: Move SDL2 sources to correct folder
      shell: powershell
      run: |
        cd ${{github.workspace}}\libs
        ls  
