name: CMake-Windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
      
    - name: sync submodules to master
      shell: bash
      run: git submodule foreach git pull origin master
    
    - name: Download SDL sources
      shell: bash
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - uses: actions/upload-artifact@v2
      with:
        name: pemsa-linux
        path: dist/
    
